# Generated by Django 4.0.4 on 2022-04-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mannequin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('height', models.FloatField(blank=True)),
                ('neck', models.FloatField(blank=True)),
                ('shoulders', models.FloatField(blank=True)),
                ('bust', models.FloatField(blank=True)),
                ('sleeves', models.FloatField(blank=True)),
                ('waist', models.FloatField(blank=True)),
                ('hips', models.FloatField(blank=True)),
                ('thighs', models.FloatField(blank=True)),
                ('legs', models.FloatField(blank=True)),
                ('shoesize', models.FloatField(blank=True)),
                ('weight', models.FloatField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='mannequins')),
            ],
        ),
    ]
