# Generated by Django 4.0.4 on 2022-04-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mannequins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mannequin',
            name='bust',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mannequin',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mannequin',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mannequin',
            name='hips',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mannequin',
            name='legs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mannequin',
            name='neck',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mannequin',
            name='shoesize',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mannequin',
            name='shoulders',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mannequin',
            name='sleeves',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mannequin',
            name='thighs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mannequin',
            name='waist',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mannequin',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
