# Generated by Django 4.0.4 on 2022-04-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mannequins', '0002_alter_mannequin_bust_alter_mannequin_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mannequin',
            name='sex',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mannequin',
            name='height',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
