# Generated by Django 4.0.4 on 2022-05-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_customer_order_shippinginfo_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippinginfo',
            old_name='state',
            new_name='phone',
        ),
    ]
