# Generated by Django 4.0.4 on 2022-04-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(max_length=128)),
                ('collection', models.CharField(max_length=128)),
                ('biographie', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='designers')),
            ],
        ),
    ]
