# Generated by Django 4.0.4 on 2022-04-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designer',
            old_name='photo',
            new_name='thumbnail',
        ),
    ]
